/**
 * DEMO DEVICE GATE (issue #66). The "try it" demo is a MOBILE PWA experience —
 * installed to the Home Screen, driven by touch. On desktop it's a poor showcase
 * (no install, hover/pointer UI that doesn't match), so a DESKTOP visitor who
 * reaches a demo path (`?demo`, or the demo-by-default `?app` browser load) is
 * gated OUT of the demo and shown THIS panel instead of a broken mobile-on-mouse
 * session. It hands the visit off to the phone: "open it on your phone" + a QR
 * code to the demo URL (design decision (a) in #66).
 *
 * IMPORTANT — this is an ACCESS gate, not a change to demo isolation. The gate
 * decision lives in demo-mode.ts (`isDemoDeviceGated()` = demo session AND the
 * device isn't touch/coarse). App.tsx renders this panel INSTEAD of booting
 * <AppInner>, so a gated desktop visitor never seeds/opens a demo session at all
 * — and, because evaluateDemoMode is unchanged, is never routed onto the REAL
 * `learning-chinese-user` jar either.
 *
 * The gate is CLIENT-SIDE ONLY: the site is static Cloudflare Pages with no
 * runtime server, so there is nothing to enforce server-side — a capability
 * check in the browser is the whole mechanism.
 *
 * Self-contained + lean: the QR is generated by the tiny local encoder in
 * utils/qr.ts (no npm dependency, per #66), imported LAZILY so it never touches
 * the installed PWA's critical path — this panel only mounts on the desktop-demo
 * path, which is online by definition. Localized via the app i18n (en + zh-TW),
 * with its own small EN/中 toggle since it renders above the profile-scoped
 * LanguageContext.
 */
import { lazy, Suspense, useMemo, useState } from 'react';
import { LanguageContext, useT, type Language } from './i18n/index.ts';

const DemoGateQr = lazy(() => import('./DemoGateQr.tsx'));

// The demo URL to hand off to the phone. Always the EXPLICIT `?app&demo` form so
// the phone lands in the demo regardless of how the desktop visitor arrived
// (bare `?app` demo-by-default, or `?demo`). Same-origin as the current page, so
// scanning it on a phone hits the same deployment.
function demoUrl(): string {
  try {
    const u = new URL(location.href);
    u.search = '';
    u.searchParams.set('app', '');
    u.searchParams.set('demo', '');
    // URLSearchParams renders empty values as `app=&demo=`; normalise to the
    // bare-flag form the app reads (`?app&demo`).
    return `${u.origin}${u.pathname}?app&demo`;
  } catch {
    return 'https://learnchinese.hsu.mobi/?app&demo';
  }
}

// Same geo-ish default as the landing page: Asian timezone or a zh browser
// language → 中文, else English.
function defaultLang(): Language {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    if (tz.startsWith('Asia/')) return 'zh-TW';
  } catch { /* no Intl tz — fall through */ }
  if (typeof navigator !== 'undefined' && navigator.language?.toLowerCase().startsWith('zh')) return 'zh-TW';
  return 'en';
}

function DemoGateInner({ url }: { url: string }) {
  const t = useT();
  return (
    <div className="demo-gate">
      <div className="demo-gate__card">
        <p className="demo-gate__eyebrow">{t('demo.gate.eyebrow')}</p>
        <h1 className="demo-gate__title">{t('demo.gate.title')}</h1>
        <p className="demo-gate__body">{t('demo.gate.body')}</p>
        <div className="demo-gate__qr">
          <Suspense fallback={<div className="demo-gate__qr-skeleton" aria-hidden="true" />}>
            <DemoGateQr url={url} alt={t('demo.gate.qrAlt')} />
          </Suspense>
          <p className="demo-gate__scan">{t('demo.gate.scan')}</p>
        </div>
        <p className="demo-gate__urllabel">{t('demo.gate.urlLabel')}</p>
        <a className="demo-gate__url" href={url}>{url}</a>
      </div>
    </div>
  );
}

export default function DemoGate() {
  const [lang, setLang] = useState<Language>(defaultLang);
  const url = useMemo(() => demoUrl(), []);
  return (
    <LanguageContext.Provider value={lang}>
      <div className="demo-gate__wrap" lang={lang}>
        <div className="demo-gate__langtoggle" role="group" aria-label="Language">
          <button
            className={`demo-gate__lang-btn${lang === 'en' ? ' is-active' : ''}`}
            aria-pressed={lang === 'en'}
            onClick={() => setLang('en')}
          >EN</button>
          <button
            className={`demo-gate__lang-btn${lang === 'zh-TW' ? ' is-active' : ''}`}
            aria-pressed={lang === 'zh-TW'}
            onClick={() => setLang('zh-TW')}
          >中</button>
        </div>
        <DemoGateInner url={url} />
      </div>
    </LanguageContext.Provider>
  );
}
