import { describe, it, expect } from 'vitest';
import { qrMatrix, qrToSvgPath } from '../qr.ts';

// The demo device gate (issue #66) hands a desktop visitor a QR to the demo URL,
// generated by the from-scratch encoder in qr.ts (no npm dependency, per the
// #66 "keep the shell lean" constraint). These tests lock the encoder's output
// so a regression in the GF(256)/Reed–Solomon/placement/format machinery can't
// silently ship an UNSCANNABLE code. The golden matrix below was cross-checked
// against the reference `qrcode` npm encoder (level M, mask 0) AND decoded back
// to the exact URL with `jsQR` during development.

const DEMO_URL = 'https://learnchinese.hsu.mobi/?app&demo';

// Golden version-3 (29×29) matrix for DEMO_URL, level M, mask 0. Verified
// scannable. '1' = dark module.
const GOLDEN_V3 = [
  '11111110010100110001001111111',
  '10000010101001110001001000001',
  '10111010001000000000101011101',
  '10111010001010110010001011101',
  '10111010100001110001001011101',
  '10000010010011110111001000001',
  '11111110101010101010101111111',
  '00000000011001101110100000000',
  '10101010011111001111100010010',
  '01011001001110000000011001001',
  '10110111000101001100010000111',
  '00010001010001110101111100010',
  '10101010100110100100111101011',
  '10000000100100001000111001001',
  '00001110110101001000001111011',
  '00110001010110010110001101010',
  '00100011100000000100011001011',
  '00010101110101001000111001101',
  '10000011011000100100000110011',
  '01110101111001110111110001010',
  '10001110100000101100111110000',
  '00000000100010101101100010111',
  '11111110000101000111101011011',
  '10000010000110001100100011001',
  '10111010111000010100111110011',
  '10111010001011000001100110111',
  '10111010100001000011000111001',
  '10000010001000101111111100010',
  '11111110100101011111111100011',
];

function toStrings(m: boolean[][]): string[] {
  return m.map((row) => row.map((c) => (c ? '1' : '0')).join(''));
}

describe('qrMatrix', () => {
  it('encodes the demo URL to the verified-scannable version-3 golden matrix', () => {
    expect(toStrings(qrMatrix(DEMO_URL))).toEqual(GOLDEN_V3);
  });

  it('picks the smallest version that fits (short → v1, longer → higher)', () => {
    // size = version*4 + 17.
    expect(qrMatrix('x').length).toBe(21); // v1
    // A ~72-byte URL no longer fits v1–v4; lands on v5 (37×37) or v6.
    const longUrl = 'https://example.com/some/longer/path?with=query&and=more&params=here123';
    const size = qrMatrix(longUrl).length;
    expect(size).toBeGreaterThanOrEqual(37);
  });

  it('produces a square matrix with the three finder patterns intact', () => {
    const m = qrMatrix(DEMO_URL);
    const n = m.length;
    // Finder = 7×7 with a dark border ring; check the top-left, top-right and
    // bottom-left corners each have the dark outer ring corner.
    for (const [r0, c0] of [[0, 0], [0, n - 7], [n - 7, 0]] as const) {
      expect(m[r0][c0]).toBe(true); // top-left of the finder ring is dark
      expect(m[r0 + 6][c0 + 6]).toBe(true); // opposite ring corner dark
      expect(m[r0 + 1][c0 + 1]).toBe(false); // the light ring inside
    }
  });

  it('throws (rather than emit a broken code) for a payload too large for v≤6', () => {
    expect(() => qrMatrix('a'.repeat(200))).toThrow(/too large/);
  });
});

describe('qrToSvgPath', () => {
  it('renders one square per dark module and sizes the viewBox with the quiet zone', () => {
    const m = qrMatrix(DEMO_URL);
    const { d, size } = qrToSvgPath(m, 2);
    expect(size).toBe(m.length + 4); // matrix + 2*quiet each side
    const darkCount = m.flat().filter(Boolean).length;
    // One "M…z" sub-path per dark module.
    expect((d.match(/z/g) || []).length).toBe(darkCount);
    expect(d.length).toBeGreaterThan(0);
  });
});
